# Generated by Django 4.0.1 on 2022-01-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Andrey Plaha', max_length=255),
        ),
    ]
